DataDog/datadog-ci-rb

docs/DevelopmentGuide.md
- Documents test matrix
- Documents how to work with appraisals
**Motivation**
Improving edveloper experience
=> improve contribution documentation

lib/datadog/ci.rb, lib/datadog/ci/contrib/cucumber/integration.rb, lib/datadog/ci/contrib/minitest/integration.rb, lib/datadog/ci/contrib/rspec/integration.rb, lib/datadog/ci/ext/environment/extractor.rb
Solving circular references warnings discovered during integration testing
**Motivation**
To be able to run ddtrace in CI with datadog-ci dependency without warnings
I will publish 0.1.1 release after merging this PR to continue with phase 1 of the CI migration
Unit tests
=> Fix circular dependencies warnings

.circleci/config.yml
Closes #34
This PR adds "edge builds" that run `bundle update` for all appraisal gemfiles in order to test against latest versions of integrations. These builds are executed every weekday, they'll be used to find out any issues with dependencies updates.
**Motivation**
Bringing build infrastructure on par with main ddtrace library.
Tested by running the workflow on circle ci.
=> edge builds for integrations

lib/datadog/ci/ext/environment/providers.rb, lib/datadog/ci/ext/environment/providers/aws_code_pipeline.rb, lib/datadog/ci/transport/http.rb, sig/datadog/ci/ext/environment/providers/aws_code_pipeline.rbs, spec/support/fixtures/ci/awscodepipeline.json
Adds AWS CodePipeline support for automatic environment tags extraction
**Motivation**
Datadog CI visibility backend supports AWS CodePipeline integration now, so we add it to the library
Tested by updating fixtures from Datadog CI specs
=> [CIVIS-175] Add AWS CodePipeline support

.github/workflows/draft-release.yml
Closes #35
Update github-script action to a newer version to fix deprecation message
**Motivation**
Deprecation message appears every time this action is used
**How to test**
https://github.com/DataDog/datadog-ci-rb/actions/runs/6614787863/job/17965504994
there is no deprecation message for the latest run anymore
=> upgrade github-script action to v6

.github/workflows/build-gem.yml, .github/workflows/check.yml, .github/workflows/codeql-analysis.yml, .github/workflows/integration-test.yml, .github/workflows/yard.yml
Closes #43
Updates actions/checkout to v4
**Motivation**
Chores
Ensure that CI still runs
=> update checkout action to v4

.github/workflows/add-milestone-to-pull-requests.yml, .github/workflows/create-next-milestone.yml
Closes #50
This PR reduces the permission of the add-milestone-to-pull-requests and create-next-milestone GitHub Actions to the minimum possible.
**Motivation**
See pull requests for dd-trace-rb repository explaining the motivation:
https://github.com/DataDog/dd-trace-rb/pull/3193
https://github.com/DataDog/dd-trace-rb/pull/3194
=> reduce permissions for milestone github actions

lib/datadog/ci/recorder.rb, spec/datadog/ci/recorder_spec.rb, spec/datadog/ci/test_visibility/serializers/test_v1_spec.rb, spec/support/span_helpers.rb
Removes "_dd.measured" tags from spans in CI visibility tracer.
**Motivation**
_dd.measured tag is used for automatically generating metrics out of non-root traces. This feature is not used for CI visbility, other test tracers do not send this tag so it can be removed
No visible change in behaviour
=> Remove _dd.measured tag from spans

lib/datadog/ci/configuration/components.rb
Disables 128-bit trace_id generation for CI mode. Tracing enabled it by default in https://github.com/DataDog/dd-trace-rb/pull/3266
**Motivation**
128-bit trace ids cause message pack to fail with "Cause: bignum too big to convert into `unsigned long long'" causing agentless mode to fail completely
```bash
git clone https://github.com/DataDog/test-environment
cd test-environment
yarn
cd dd-trace-rb/jekyll
bundle add ddtrace --git "https://github.com/DataDog/dd-trace-rb.git" --branch "master" --skip-install
bundle install --path .bundle
cd ../..
yarn test dd-trace-rb/jekyll.test.js
cd dd-trace-rb/devdocs
bundle add ddtrace --git "https://github.com/DataDog/dd-trace-rb.git" --branch "master" --skip-install
bundle install --path .bundle …
```
=> disable 128-bit trace id generation in CI mode

lib/datadog/ci.rb, lib/datadog/ci/configuration/components.rb, lib/datadog/ci/null_span.rb, lib/datadog/ci/recorder.rb, sig/datadog/ci.rbs, sig/datadog/ci/null_span.rbs, sig/datadog/ci/recorder.rbs, spec/datadog/ci/configuration/components_spec.rb, spec/datadog/ci/null_span_spec.rb, spec/datadog/ci/recorder_spec.rb, spec/support/ci_mode_helpers.rb
Couple of small but important fixes regarding CI mode configuration:
- currently when using manual API and setting `settings.ci.enabled` to `false` (when running tests locally) leads to a complete failure because `@ci_recorder` is nil. Now we are creating the recorder in disabled state in this case to stop tracing but preserving the behaviour. 
- In order to make it more bearable without adding null checks everywhere a new span type is provided - `NullSpan` which is an implementation of NullObject pattern.
- we will disable test suite level visibility always when we detect old agent version that does not support event protocol
=> Skip tracing when CI mode disabled and manual API is used

lib/datadog/ci.rb, lib/datadog/ci/context/global.rb, lib/datadog/ci/ext/app_types.rb, lib/datadog/ci/ext/test.rb, lib/datadog/ci/recorder.rb, lib/datadog/ci/test_module.rb, lib/datadog/ci/test_session.rb, lib/datadog/ci/test_visibility/serializers/base.rb, lib/datadog/ci/test_visibility/serializers/factories/test_suite_level.rb, lib/datadog/ci/test_visibility/serializers/test_module.rb, lib/datadog/ci/test_visibility/serializers/test_v2.rb, sig/datadog/ci.rbs, sig/datadog/ci/context/global.rbs, sig/datadog/ci/ext/app_types.rbs, sig/datadog/ci/ext/test.rbs, sig/datadog/ci/recorder.rbs, sig/datadog/ci/test_module.rbs, sig/datadog/ci/test_visibility/serializers/test_module.rbs, spec/datadog/ci/context/global_spec.rb, spec/datadog/ci/recorder_spec.rb, spec/datadog/ci/test_module_spec.rb, spec/datadog/ci/test_visibility/serializers/test_module_spec.rb, spec/datadog/ci/test_visibility/serializers/test_v2_spec.rb, spec/datadog/ci_spec.rb, spec/support/tracer_helpers.rb
Adds test modules support as described by Datadog docs [here](https://docs.datadoghq.com/continuous_integration/explorer/?tab=testruns#module).
For Ruby test frameworks module will be synonymous with session (just like in JS), so only one module per process can be active at any given time.
=> Test module support

lib/datadog/ci/configuration/components.rb, lib/datadog/ci/ext/settings.rb, sig/datadog/ci/configuration/components.rbs, sig/datadog/ci/ext/settings.rbs, spec/datadog/ci/configuration/components_spec.rb
Closes #62
Validates that DD_SITE variable has one of the allowed values as defined by [docs](https://docs.datadoghq.com/getting_started/site/) and emits warning in logs otherwise
**Motivation**
More often than not users are confused by DD_SITE setting required by Agentless mode (when not using default datadog site). 
This validation is supposed to help users to debug this issue themselves by calling out invalid setting in the logs.
Unit tests are provided or: set DD_SITE to any wrong value and run tests with CI visibility enabled
=> Validate DD_SITE variable

README.md
Closes #63
Adds a short instruction to README about configuring webmock with CI visibility to allow HTTP requests to agent or Datadog backend
=> Document how to use WebMock with datadog-ci

README.md, lib/datadog/ci.rb, lib/datadog/ci/contrib/cucumber/configuration/settings.rb, lib/datadog/ci/contrib/cucumber/formatter.rb, lib/datadog/ci/contrib/minitest/configuration/settings.rb, lib/datadog/ci/contrib/minitest/hooks.rb, lib/datadog/ci/contrib/rspec/configuration/settings.rb, lib/datadog/ci/contrib/rspec/example.rb, lib/datadog/ci/recorder.rb, sig/datadog/ci.rbs, sig/datadog/ci/recorder.rbs, spec/datadog/ci/contrib/cucumber/instrumentation_spec.rb, spec/datadog/ci/contrib/minitest/instrumentation_spec.rb, spec/datadog/ci/contrib/rspec/instrumentation_spec.rb, spec/datadog/ci/recorder_spec.rb, spec/datadog/ci_spec.rb, spec/support/tracer_helpers.rb, vendor/rbs/ddtrace/0/datadog/core.rbs, vendor/rbs/ddtrace/0/datadog/core/configuration/option_definition.rbs
This PR cleans up some of the confusion caused by service_name and operation_name parameters in CI tracing public API:
- service_name is renamed to service
- operation_name is removed from manual API
- operation_name settings option is deprecated
**Motivation**
operation_name is a setting that is used for internal span naming only, with event-based encoding it does not reach backend at all - so it is very confusing to keep it in the public API
service_name parameter was named after the legacy contrib setting, but actually it is called service everywhere nowadays (including environment variable DD_SERVICE)
=> Deprecate operation name setting, change service_name to service in public API

lib/datadog/ci/test_visibility/serializers/base.rb, lib/datadog/ci/test_visibility/transport.rb, sig/datadog/ci/test_visibility/serializers/base.rbs, spec/datadog/ci/test_visibility/serializers/test_module_spec.rb, spec/datadog/ci/test_visibility/serializers/test_v1_spec.rb, spec/datadog/ci/test_visibility/transport_spec.rb
**Motivation**
Currently we don't see any feedback when invalid events are being discarded during serialization phase. This behaviour was inherited from ddtrace-rb where such errors are only emitted in debug mode.
For CI visibility library it is very important to report all the spans, so skipping invalid spans is a serious error that requires an action.
- Elevates logging level for invalid spans skipping to WARN
- Now event serializer stores validation errors so that they could be logged for easier debugging
=> support validation errors for CI spans

.github/workflows/yard.yml, .yardopts, Gemfile, README.md, docs/Deprecation.md, docs/PublicApi.md, lib/datadog/ci.rb, lib/datadog/ci/contrib/cucumber/configuration/settings.rb, lib/datadog/ci/contrib/minitest/configuration/settings.rb, lib/datadog/ci/contrib/rspec/configuration/settings.rb, lib/datadog/ci/contrib/settings.rb, lib/datadog/ci/ext/test.rb, yard/extensions.rb, yard/templates/default/docstring/html/deprecated.erb, yard/templates/default/docstring/setup.rb
Closes #37
Adds YARD documentation to this library
**Motivation**
1.0 release and general availability are getting close so we need to prepare documentation
Run `bundle exec rake docs` locally and examine `doc/index.html`
=> generate YARD documentation

lib/datadog/ci/test_visibility/recorder.rb, spec/datadog/ci/test_visibility/recorder_spec.rb
Fixes https://github.com/DataDog/dd-trace-rb/issues/3314
Prevents Datadog::CI::Ext::Environment from collecting environment information and validating it if CI mode is not enabled.
**Motivation**
Regression introduced in 0.5.0 release: ddtrace started to emit error logs in production about CI environment tags not being provided
Run ruby application with ddtrace in production mode
=> do not collect environment tags when CI is not enabled

integration/app/spec/basic_spec.rb, integration/app/spec/shared_examples.rb, integration/app/spec/spec_helper.rb, lib/datadog/ci/contrib/rspec/configuration/settings.rb, lib/datadog/ci/contrib/rspec/example.rb, lib/datadog/ci/contrib/rspec/example_group.rb, lib/datadog/ci/contrib/rspec/ext.rb, lib/datadog/ci/contrib/rspec/patcher.rb, lib/datadog/ci/contrib/rspec/runner.rb, lib/datadog/ci/ext/test.rb, lib/datadog/ci/test.rb, lib/datadog/ci/test_session.rb, lib/datadog/ci/test_visibility/recorder.rb, sig/datadog/ci.rbs, sig/datadog/ci/contrib/rspec/example_group.rbs, sig/datadog/ci/contrib/rspec/ext.rbs, sig/datadog/ci/contrib/rspec/runner.rbs, sig/datadog/ci/ext/test.rbs, sig/datadog/ci/test.rbs, sig/datadog/ci/test_visibility/recorder.rbs, spec/datadog/ci/contrib/rspec/instrumentation_spec.rb, spec/datadog/ci/contrib/rspec/some_shared_examples.rb, spec/datadog/ci/test_session_spec.rb, spec/datadog/ci/test_spec.rb, spec/datadog/ci/test_visibility/recorder_spec.rb, spec/support/tracer_helpers.rb, vendor/rbs/rspec/0/rspec.rbs
Adds RSpec instrumentation for test suite level visibility
This change is mostly compatible with current rspec instrumentation except one important change:
test suite name for a test is now `metadata[:example_group][:rerun_file_path]` instead of `metadata[:example_group][:file_path]`. The reason for that is if ExampleGroup is defined in shared examples inside a context like that:
```ruby
RSpec.shared_examples "Testing shared examples" do
context "shared examples" do
it "adds 1 and 1" do
expect(1 + 1).to eq(2)
end
end
end
```
...then `file_path` contains the path of shared examples file whereas `rerun_file_path` contains the path of test file.
There are open source projects I used for testing: …
=> [CIVIS-7950] Add rspec instrumentation for test suite level visibility

lib/datadog/ci/contrib/cucumber/formatter.rb, sig/datadog/ci/contrib/cucumber/formatter.rbs
Simplifies test suite failure tracking for Cucumber integration: instead of counting how many tests failed per current test suite, we will mark test suite as failed if any of the tests failed.
This will eliminate additional variable and condition checks that could cause bugs.
**Motivation**
Making test suite failure tracking for Cucumber simpler and similar to Minitest implementation.
Tracking failure counts still exists for test session for the following reasons:
- we don't have to reset this number during the test session
- we use it only for Cucumber < 8 as since Cucumber 8.0 we have a proper support for test session result
Unit tests stay the same, it is a refactoring without behaviour change
=> [Cucumber contrib] remove tracking failed tests count per test suite, mark test suite as failed if any test fails

gemfiles/ruby_3.3_cucumber_3.gemfile.lock, gemfiles/ruby_3.3_cucumber_4.gemfile.lock, gemfiles/ruby_3.3_cucumber_5.gemfile.lock, gemfiles/ruby_3.3_cucumber_6.gemfile.lock, gemfiles/ruby_3.3_cucumber_7.gemfile.lock, gemfiles/ruby_3.3_cucumber_8.gemfile.lock, gemfiles/ruby_3.3_minitest_5.gemfile.lock, gemfiles/ruby_3.3_rspec_3.gemfile.lock, lib/datadog/ci/contrib/cucumber/formatter.rb, lib/datadog/ci/contrib/minitest/hooks.rb, lib/datadog/ci/contrib/rspec/example.rb, lib/datadog/ci/ext/environment/providers/local_git.rb, lib/datadog/ci/ext/test.rb, lib/datadog/ci/utils/git.rb, sig/datadog/ci/ext/environment/providers/local_git.rbs, sig/datadog/ci/ext/test.rbs, sig/datadog/ci/utils/git.rbs, spec/datadog/ci/contrib/cucumber/instrumentation_spec.rb, spec/datadog/ci/contrib/minitest/instrumentation_spec.rb, spec/datadog/ci/contrib/rspec/instrumentation_spec.rb, spec/datadog/ci/utils/git_spec.rb
Adds support to `test.source.file` and `test.source.start` tags that are used by source code integration to show test's source in Datadog UI:
**Motivation**
To achieve feature parity with other CI visibility libraries and provide basis for CODEOWNERS support.
Run ruby tests from https://github.com/anmarchenko/middleman with your Datadog API key and check that source code integration works.
=> [CIVIS-3035] Source code tags integration

lib/datadog/ci/contrib/cucumber/formatter.rb, lib/datadog/ci/contrib/cucumber/instrumentation.rb, lib/datadog/ci/ext/test.rb, lib/datadog/ci/null_span.rb, lib/datadog/ci/span.rb, lib/datadog/ci/test.rb, sig/datadog/ci/contrib/cucumber/formatter.rbs, sig/datadog/ci/ext/test.rbs, sig/datadog/ci/span.rbs, spec/datadog/ci/contrib/cucumber/features/step_definitions/steps.rb, spec/datadog/ci/contrib/cucumber/features/with_parameters.feature, spec/datadog/ci/contrib/cucumber/instrumentation_spec.rb, spec/datadog/ci/span_spec.rb, vendor/rbs/cucumber/0/cucumber.rbs
Adds parametrized test support for cucumber-rby (version 4 and above):
**Motivation**
Currently all test runs with [scenario outline](https://cucumber.io/docs/gherkin/reference/#scenario-outline) have the same test fingerprint and treated as a single test being run multiple times. We should use `test.parameters` tag to distinguish these tests from each other
- Cucumber 3.0 does not have a way to extract examples but in Cucumber 3.0 all scenario outline runs have "(Example #N)" prefix so they are unique
- JSON hash is set using JSON.stringify because Cucumebr examples are built using strings, so I am sure that these parameters have proper string representations
Tested using https://github.com/anmarchenko/jekyll
=> [CIVIS-7722] Parametrized tests support for cucumber

lib/datadog/ci/contrib/rspec/example.rb, lib/datadog/ci/span.rb, spec/datadog/ci/contrib/rspec/instrumentation_spec.rb, spec/datadog/ci/contrib/rspec/some_shared_examples.rb
Adds deduplication for RSpec examples using "test.parameters.metadata" and "scoped_id" provided by rspec which is a stable label assigned to each example:
**Motivation**
Shared examples and dynamically generated examples with the same name were having the same fingerprint in Datadog test runs view.
**Why does it work like that?**
RSpec has many ways to define test with parameters.
1. Using shared examples ([source](https://github.com/anmarchenko/rubocop/blob/b61887841df781e4c34f1bef5c6f2859273737a7/spec/rubocop/cop/lint/literal_in_interpolation_spec.rb)):
```ruby
shared_examples 'literal interpolation' do |literal, expected = literal|
it "registers an offense for #{literal} in interpolation " \
'and removes interpolation around it' do
expect_offense(<<~'RUBY', …
```
=> [CIVIS-7722] Deduplicate dynamically generated RSpec examples using metadata.scoped_id

lib/datadog/ci/test_visibility/recorder.rb
Replaces deprecated span_type option with type when using Datadog::Tracing.trace
**Motivation**
span_type is removed in ddtrace 2.0:
https://github.com/DataDog/dd-trace-rb/pull/3330
=> replace span_type option with type for Datadog::Tracing.trace

spec/datadog/ci/contrib/cucumber/instrumentation_spec.rb, spec/datadog/ci/contrib/minitest/instrumentation_spec.rb, spec/datadog/ci/contrib/rspec/instrumentation_spec.rb, spec/datadog/ci/test_visibility/recorder_spec.rb, spec/datadog/ci/transport/api/builder_spec.rb
There are more occurences of deprecated span_type method in specs, remove them before ddtrace 2.0 release
=> remove occurences of span_type in specs

lib/datadog/ci/contrib/cucumber/formatter.rb, lib/datadog/ci/contrib/minitest/hooks.rb, lib/datadog/ci/contrib/rspec/example.rb, lib/datadog/ci/contrib/rspec/example_group.rb, lib/datadog/ci/contrib/rspec/runner.rb, sig/datadog/ci/contrib/cucumber/formatter.rbs, sig/datadog/ci/contrib/rspec/example.rbs, sig/datadog/ci/contrib/rspec/example_group.rbs, sig/datadog/ci/contrib/rspec/runner.rbs, spec/datadog/ci/contrib/cucumber/features/failing.feature, spec/datadog/ci/contrib/cucumber/instrumentation_spec.rb, spec/datadog/ci/contrib/minitest/instrumentation_spec.rb, spec/datadog/ci/contrib/rspec/instrumentation_spec.rb, vendor/rbs/cucumber/0/cucumber.rbs, vendor/rbs/rspec/0/rspec.rbs
Changes test suite name and test name definitions to improve UX and make test dashboard look nicer.
**Cucumber**
- uses feature name as a prefix for test suite name
Before:
After:
**RSpec**
- uses top-level example group description as test suite name
- removes top-level example group description from test name to avoid repetition
Before:
After:
**Minitest**
- remove test suite class name from test.name tag to avoid unnecessary repetition
Before:
After:
**Motivation**
Current test suite names and test names are not easily readable in test runs table
Tested using a number of open source projects (see screenshots above)
=> [CIVIS-8548] make test suite names more readable

lib/datadog/ci.rb, lib/datadog/ci/null_span.rb, lib/datadog/ci/span.rb, lib/datadog/ci/test_visibility/null_recorder.rb, lib/datadog/ci/test_visibility/recorder.rb, lib/datadog/ci/test_visibility/serializers/base.rb, lib/datadog/ci/test_visibility/serializers/span.rb, lib/datadog/ci/test_visibility/serializers/test_module.rb, lib/datadog/ci/test_visibility/serializers/test_session.rb, lib/datadog/ci/test_visibility/serializers/test_suite.rb, lib/datadog/ci/test_visibility/serializers/test_v1.rb, sig/datadog/ci.rbs, sig/datadog/ci/null_span.rbs, sig/datadog/ci/span.rbs, sig/datadog/ci/test_visibility/null_recorder.rbs, sig/datadog/ci/test_visibility/recorder.rbs, sig/datadog/ci/test_visibility/serializers/base.rbs, spec/datadog/ci/null_span_spec.rb, spec/datadog/ci/span_spec.rb, spec/datadog/ci/test_visibility/recorder_spec.rb, spec/datadog/ci_spec.rb, vendor/rbs/ddtrace/0/datadog/tracing/span_operation.rbs
dd-trace-rb recently dropped span_type method for SpanOperation. In order to avoid confusion, I do the same in Datadog::CI context.
For serializers span_type method stays to distinguish it from event type (that can have slightly different meaning). To reduce confusion for future self and other contributors, `Serializers::Base#type` is renamed to `Serializers::Base#event_type`
**Motivation**
Reducing confusion and surprise level of our API
=> [CIVIS-8333] get rid of span_type in tracer-related models

lib/datadog/ci/concurrent_span.rb, lib/datadog/ci/contrib/cucumber/formatter.rb, lib/datadog/ci/contrib/minitest/hooks.rb, lib/datadog/ci/contrib/minitest/runnable.rb, lib/datadog/ci/contrib/rspec/example.rb, lib/datadog/ci/contrib/rspec/example_group.rb, lib/datadog/ci/test.rb, lib/datadog/ci/test_suite.rb, sig/datadog/ci/concurrent_span.rbs, sig/datadog/ci/contrib/cucumber/formatter.rbs, sig/datadog/ci/contrib/minitest/hooks.rbs, sig/datadog/ci/contrib/rspec/example_group.rbs, sig/datadog/ci/test.rbs, sig/datadog/ci/test_suite.rbs, spec/datadog/ci/contrib/cucumber/features/passing.feature, spec/datadog/ci/contrib/cucumber/features/skipped.feature, spec/datadog/ci/contrib/cucumber/features/step_definitions/steps.rb, spec/datadog/ci/contrib/cucumber/instrumentation_spec.rb, spec/datadog/ci/contrib/minitest/instrumentation_spec.rb, spec/datadog/ci/contrib/rspec/instrumentation_spec.rb, spec/datadog/ci/test_spec.rb, spec/datadog/ci/test_suite_spec.rb, vendor/rbs/cucumber/0/cucumber.rbs
Solves multiple issues around skipped tests and test suites:
- all frameworks now correctly report test suite as skipped if there are no passed and no failed tests
- Cucumber now correctly reports undefined scenarios as skipped (if not running in strict mode)
- Cucumber strict mode support: in strict mode undefined scenarios are marked as failed
- RSpec: previously pending tests with failures were reported without any status, now they are reported as skipped
**Motivation**
Wrapping up last bugs and problems before GA for Ruby
As Ruby test frameworks mostly do not provide statuses of test suites (and do not care much about the concept of a test suite), now we track count of passed/failed/skipped tests per test suite in `Datadog::CI::TestSuite` …
=> [CIVIS-8549] better skipped tests and suites support

lib/datadog/ci/contrib/minitest/patcher.rb, lib/datadog/ci/contrib/minitest/reporter.rb, lib/datadog/ci/contrib/minitest/runner.rb, sig/datadog/ci/contrib/minitest/runner.rbs
Fixes rails parallel test executor instrumentation that was broken since I added ci-queue support to minitest framework.
**Why was this broken?**
In the previous episode of "Datadog figures out how to instrument all possible ways one can use Minitest" we watched [minitest-reporters interfering with `datadog-ci` plugin](https://github.com/DataDog/datadog-ci-rb/pull/110) which caused me to remove plugin and instrument Minitest::CompositeReporter to mark start and end of test sessions.
But... (suspenseful music) there is a twist!
Here is the `Minitest.run` [method](https://github.com/minitest/minitest/blob/master/lib/minitest.rb#L143) (important parts only):
```ruby
def self.run args = []
self.load_plugins unless args.delete("--no-plugins") || ENV["MT_NO_PLUGINS"] …
```
=> minitest: fix rails parallel test runner

.standard.yml, .standard_todo.yml, lib/datadog/ci/configuration/settings.rb, lib/datadog/ci/contrib/cucumber/formatter.rb, lib/datadog/ci/contrib/cucumber/integration.rb, lib/datadog/ci/contrib/minitest/integration.rb, lib/datadog/ci/contrib/rspec/example.rb, lib/datadog/ci/contrib/rspec/integration.rb, lib/datadog/ci/ext/environment.rb, lib/datadog/ci/ext/environment/providers/base.rb, lib/datadog/ci/ext/environment/providers/bitbucket.rb, lib/datadog/ci/test.rb, lib/datadog/ci/test_visibility/context/global.rb, lib/datadog/ci/test_visibility/null_recorder.rb, lib/datadog/ci/test_visibility/recorder.rb, lib/datadog/ci/test_visibility/serializers/base.rb, lib/datadog/ci/test_visibility/transport.rb, lib/datadog/ci/transport/http.rb, lib/datadog/ci/version.rb, spec/datadog/ci/test_visibility/null_recorder_spec.rb, spec/support/tracer_helpers.rb
Migrates this library to use Ruby 2.7 syntax: safe navigation operator, filter_map method
**Motivation**
We don't support older rubies anymore and can simplify some code
=> [CIVIS-2985] use ruby 2.7 syntax

README.md, lib/datadog/ci/contrib/cucumber/configuration/settings.rb, lib/datadog/ci/contrib/cucumber/ext.rb, lib/datadog/ci/contrib/minitest/configuration/settings.rb, lib/datadog/ci/contrib/minitest/ext.rb, lib/datadog/ci/contrib/rspec/configuration/settings.rb, lib/datadog/ci/contrib/rspec/ext.rb, lib/datadog/ci/contrib/settings.rb, sig/datadog/ci/contrib/cucumber/ext.rbs, sig/datadog/ci/contrib/minitest/ext.rbs, sig/datadog/ci/contrib/rspec/ext.rbs, sig/datadog/ci/contrib/settings.rbs
Removes deprecated config option for version 1.0
=> [CIVIS-2985] remove operation_name from integrations

README.md
Adds note to README on how to configure VCR with datadog-ci
**Motivation**
One of our users pointed out that we lack instructions on how to make datadog-ci work when using VCR gem
=> Add note to README on using VCR

lib/datadog/ci/configuration/components.rb, lib/datadog/ci/ext/transport.rb, lib/datadog/ci/transport/api/agentless.rb, lib/datadog/ci/transport/api/builder.rb, lib/datadog/ci/transport/api/evp_proxy.rb, sig/datadog/ci/configuration/components.rbs, sig/datadog/ci/ext/transport.rbs, sig/datadog/ci/transport/api/agentless.rbs, sig/datadog/ci/transport/api/builder.rbs, sig/datadog/ci/transport/api/evp_proxy.rbs, spec/datadog/ci/configuration/components_spec.rb, spec/datadog/ci/transport/api/agentless_spec.rb, spec/datadog/ci/transport/api/builder_spec.rb, spec/datadog/ci/transport/api/evp_proxy_spec.rb, spec/support/contexts/ci_mode.rb
Enables compression of payloads that this library sends to Datadog Agent by using `/evp_proxy/v4/` endpoint when it is available.
**Motivation**
Datadog Agent v7.52.0 is going to support forwarding gzip headers to the backend. We leverage this new capability to make our network calls more efficient and reduce overhead for users when running tests.
This change also contains some refactoring for Api clients:
- CiTestCycle is renamed to Agentless
- Client building logic moved from `Datadog::CI::Configuration::Components` to `Datadog::CI::Transport::Api::Builder` where it should have been
Tested locally with dev build of Datadog Agent, unit tests are provided
=> [CIVIS-8782] gzip agent payloads support via evp_proxy/v4

lib/datadog/ci/contrib/cucumber/formatter.rb, lib/datadog/ci/contrib/minitest/runner.rb, lib/datadog/ci/contrib/rspec/runner.rb, spec/datadog/ci/contrib/cucumber/instrumentation_spec.rb, spec/datadog/ci/contrib/minitest/instrumentation_spec.rb, spec/datadog/ci/contrib/rspec/instrumentation_spec.rb
Fixes customer-reported issue with flaky test detection after test suite level visibility release.
**Bug description**
Currently `test_module_end` events have the same name as `test_session_end` which could be different between test runs: we use test command value this and test command could include variable data (like --seed param). The problem is that test module name is part of test fingerprint, and unstable fingerprints make flaky test detection impossible.
**How is it fixed?**
We change test module name to be just the test framework name (minitest, rspec, or cucumber). NOTE: This change will cause fingerprint updates for all current tests.
=> use framework name as test module name to make test fingerprints stable

lib/datadog/ci/test_visibility/context/global.rb, lib/datadog/ci/test_visibility/recorder.rb, sig/datadog/ci/test_visibility/context/global.rbs, sig/datadog/ci/test_visibility/recorder.rbs, spec/datadog/ci/test_visibility/context/global_spec.rb, spec/datadog/ci/test_visibility/recorder_spec.rb
Makes test suite assignment more robust by assigning the single runinng test suite to a test when no test suite found by name.
**Motivation**
There are cases where minitest test suite names fluctuate from test to test because of using external libraries like shoulda-context and/or activesupport concerns. While https://github.com/DataDog/datadog-ci-rb/pull/134 fixed most of these cases there are still a very small chance of some test cases (inside anonymous classes?) that are skipped because of missing test suite id.
Thankfully, if minitest executes tests sequentially, there should be only one test suite running at a time: we can use it to assign "lost tests" to whichever test suite that is currently running.
=> [CIVIS-9349] assign the single running test suite for a test if none found by test suite name

lib/datadog/ci/transport/api/builder.rb, vendor/rbs/ddtrace/0/datadog/core/remote/negotiation.rbs
Removes temporary hack to suppress logging of Datadog::Core::Remote::Negotiation
=> remove temporary hack and use Core::Remote::Negotiation's new constructor param

README.md
Adds a note to README about possible issues when using minitest/autorun
**Motivation**
minitest/autorun registers at_exit hook that runs the test suite. Datadog::Core also registers at_exit hook that stops Tracing worker. As hooks are executed in LIFO order, Datadog must be required first: that way test suite is being run and then Tracing is stopped. Otherwise, tests are being run without tracing enabled.
=> add a section on correctly using tracer with minitest/autorun

lib/datadog/ci/ext/environment.rb, lib/datadog/ci/ext/transport.rb, lib/datadog/ci/git/search_commits.rb, lib/datadog/ci/utils/git.rb, sig/datadog/ci/ext/environment.rbs, sig/datadog/ci/ext/transport.rbs, sig/datadog/ci/git/search_commits.rbs, sig/datadog/ci/utils/git.rbs, spec/datadog/ci/git/search_commits_spec.rb, spec/datadog/ci/utils/git_spec.rb, vendor/rbs/ddtrace/0/datadog/core/transport/response.rbs
Adds `Datadog::CI::Git::SearchCommits` class that sends backen API request to `/api/v2/git/repository/search_commits` endpoint and gets a list of commits that are already known to the backend DB.
For now unit tests only, this class is not used yet
=> [CIVIS-2938] Add Git::SearchCommits api client

lib/datadog/ci/ext/transport.rb, lib/datadog/ci/git/local_repository.rb, lib/datadog/ci/git/search_commits.rb, lib/datadog/ci/git/upload_packfile.rb, sig/datadog/ci/ext/transport.rbs, sig/datadog/ci/git/local_repository.rbs, sig/datadog/ci/git/upload_packfile.rbs, spec/datadog/ci/git/local_repository_spec.rb, spec/datadog/ci/git/search_commits_spec.rb, spec/datadog/ci/git/upload_packfile_spec.rb
Adds `Git::UploadPackfile` class that is able to upload a single git packfile to Datadog's git API.
Makes minor changes to git_commits_rev_list and git_generate_packfiles methods to make them safer and prevent shell injections.
Unit tests are provided, otherwise this functionality is not used yet
=> [CIVIS-2938] Upload packfiles API client

Steepfile, lib/datadog/ci/git/local_repository.rb, lib/datadog/ci/git/packfiles.rb, lib/datadog/ci/git/tree_uploader.rb, sig/datadog/ci/git/local_repository.rbs, sig/datadog/ci/git/packfiles.rbs, sig/datadog/ci/git/tree_uploader.rbs, spec/datadog/ci/git/local_repository_spec.rb, spec/datadog/ci/git/packfiles_spec.rb, spec/datadog/ci/git/tree_uploader_spec.rb
Adds `Datadog::CI::Git::TreeUploader` class that performs git metadata upload
This is not done yet, there are several features coming in the next PRs:
- [add unshallowing logic](https://github.com/DataDog/datadog-ci-rb/pull/155)
- wrap TreeUploader in background worker
- start git upload process when starting test session (behind configuration flag)
- change library configuration logic to wait for git upload if `require_git` is true
Tested on https://github.com/anmarchenko/sidekiq/tree/anmarchenko/datadog-ci-visibility with the following result in debug logs:
```
D, [2024-04-09T13:06:00.880158 #11671] DEBUG -- datadog: [datadog] (/Users/andrey.marchenko/p/datadog-ci-rb/lib/datadog/ci/git/tree_uploader.rb:27:in …
```
=> [CIVIS-2938] Git tree uploader

lib/datadog/ci/git/local_repository.rb, lib/datadog/ci/git/tree_uploader.rb, sig/datadog/ci/git/local_repository.rbs, sig/datadog/ci/git/tree_uploader.rbs, spec/datadog/ci/git/local_repository_spec.rb, spec/datadog/ci/git/tree_uploader_spec.rb
Adds the following git unshallowing logic to this library:
Also implements unshallowing optimization: if all commits from the shallow repo are present in the backend, we skip the git upload alltogether.
=> [CIVIS-2863] Git repository unshallowing logic

lib/datadog/ci/itr/runner.rb, lib/datadog/ci/test_visibility/recorder.rb, lib/datadog/ci/transport/remote_settings_api.rb, lib/datadog/ci/utils/parsing.rb, sig/datadog/ci/itr/runner.rbs, sig/datadog/ci/transport/remote_settings_api.rbs, sig/datadog/ci/utils/parsing.rbs, spec/datadog/ci/test_visibility/recorder_spec.rb, spec/datadog/ci/transport/remote_settings_api_spec.rb, spec/support/contexts/ci_mode.rb
Implements default branch code coverage overhead optimization: when server adds with `require_git: true` to the library settings payload, we wait for git upload to be done and then request settings again. The ITR Runner is configured with the second settings payload.
The reason for this is that if default branch does not have many relevant code changes, running per test code coverage won't give us a lot of new information and can be skipped: thus, tests in default branch will run faster without per test code coverage overhead.
=> [CIVIS-9606] reduce ITR-induced code coverage overhead for default branch

lib/datadog/ci/ext/transport.rb, lib/datadog/ci/itr/skippable.rb, lib/datadog/ci/test_visibility/recorder.rb, sig/datadog/ci/ext/transport.rbs, sig/datadog/ci/itr/skippable.rbs, spec/datadog/ci/configuration/settings_spec.rb, spec/datadog/ci/itr/skippable_spec.rb
Add skippable tests api client: will be used in subsequent PRs to request from the backend which tests can be skipped
Unit tests only for now
=> [CIVIS-2934] skippable tests api client

README.md, docs/UpgradeGuide.md
Adds upgrade guide for users upgrading from ddtrace gem and updates readme.
**Motivation**
Next major release for Datadog ruby libraries is coming
=> [CIVIS-2985] upgrade guide for 1.0

lib/datadog/ci/test_visibility/serializers/base.rb, lib/datadog/ci/test_visibility/serializers/factories/test_level.rb, lib/datadog/ci/test_visibility/serializers/factories/test_suite_level.rb, lib/datadog/ci/test_visibility/serializers/test_v2.rb, lib/datadog/ci/test_visibility/transport.rb, sig/datadog/ci/itr/runner.rbs, sig/datadog/ci/test_visibility/serializers/base.rbs, sig/datadog/ci/test_visibility/serializers/factories/test_level.rbs, sig/datadog/ci/test_visibility/serializers/factories/test_suite_level.rbs, sig/datadog/ci/test_visibility/serializers/test_v2.rbs, sig/datadog/ci/test_visibility/transport.rbs, spec/datadog/ci/test_visibility/serializers/factories/test_suite_level_spec.rb, spec/datadog/ci/test_visibility/serializers/test_v2_spec.rb, spec/datadog/ci/test_visibility/transport_spec.rb
To show "why this test was skipped" explanation in the Datadog UI, we need to send `itr_correlation_id` field in content part of test events: this PR adds just that. 
`TestVisibility::Transport` obtains itr_correlation_id by calling a method on `ITR::Runner` directly and then passes to serializers via new `options` keyword parameter.
Tested using anmarchenko/jekyll project on dd-staging with the following result:
=> [CIVIS-9014] implement "why this test was skipped" feature by adding ITR correlation to test events

lib/datadog/ci/configuration/components.rb, lib/datadog/ci/itr/runner.rb, lib/datadog/ci/itr/skippable.rb, lib/datadog/ci/transport/remote_settings_api.rb, lib/datadog/ci/utils/test_run.rb, sig/datadog/ci/itr/runner.rbs, sig/datadog/ci/itr/skippable.rbs, sig/datadog/ci/transport/remote_settings_api.rbs, sig/datadog/ci/utils/test_run.rbs, spec/datadog/ci/itr/skippable_spec.rb, spec/datadog/ci/transport/remote_settings_api_spec.rb, spec/datadog/ci/utils/test_run_spec.rb
There are some configurations that cannot be directly identified and reported automatically. For those cases, the user must provide the configuration details to the library so CI Visibility can properly identify them. These tags affect the test fingerprint. These custom configurations are passed via DD_TAGS with a test.configuration. prefix, that is, every test.configuration.* tag will be treated as a custom configuration. 
We send these custom configurations when requesting **library settings** and **skippable tests** in `data.attributes.configurations.custom field`.
Using anmarchenko/sidekiq
Test with custom configurations:
Logs when sending skippable request:
```
D, [2024-04-24T14:02:38.210618 #19229] DEBUG -- datadog: [datadog] …
```
=> [CIVIS-9333] support custom configuration tags supplied from the environment

docs/UpgradeGuide.md, lib/datadog/ci/configuration/components.rb, lib/datadog/ci/itr/coverage/writer.rb, lib/datadog/ci/itr/runner.rb
A couple of smaller changes ahead of ITR public beta:
- more debug logging
- error handling for coverage writer: instead of silently killing the the coverage writer on errors print WARN messages and back-off
- do not skip tests when using forked test runners (to be supported later)
- disable startup logging from tracing as it is useless for test visibility mode and spams logs
=> [NO TICKET] more debug logging, do not skip tests when running in forked processes

lib/datadog/ci/configuration/settings.rb
Removes deprecated `use` alias - use `instrument` instead
=> [NO TICKET] remove deprecated use alias

lib/datadog/ci/configuration/components.rb, spec/datadog/ci/configuration/components_spec.rb
Logs an error message when tracing is disabled but test visibility is enabled.
**Motivation**
There are many cases when tracing is disabled by competing configuration (most often in `initializers` folder to disable APM in non-production environments). Currently in this cases this library continues to work silently skipping all traces. This PR fixes that by catching attention of developer: hopefully this will lead to easier onboarding.
=> log an error message if tracing is disabled but test visibility is enabled

lib/datadog/ci/ext/transport.rb, lib/datadog/ci/transport/api/agentless.rb, lib/datadog/ci/transport/gzip.rb, lib/datadog/ci/transport/http.rb, sig/datadog/ci/ext/transport.rbs, sig/datadog/ci/transport/api/agentless.rbs, sig/datadog/ci/transport/gzip.rbs, sig/datadog/ci/transport/http.rbs, spec/datadog/ci/transport/api/agentless_spec.rb, spec/datadog/ci/transport/gzip_spec.rb, spec/datadog/ci/transport/http_spec.rb
Adds capability for HTTP layer to request gzipped payload via Accept-Encoding header and decompress payloads if they are gzipped. Uses this capability for Rapid-API requests in agentless mode.
**Motivation**
Save time when fetching skippable tests for very large repos. Fetching 20k+ tests for rubocop happens in 5s with this change vs 13s before.
=> [CIVIS-9901] accept gzipped responses from API

Rakefile, lib/datadog/ci/contrib/rspec/example.rb, lib/datadog/ci/contrib/rspec/example_group.rb, lib/datadog/ci/contrib/rspec/knapsack_pro/extension.rb, lib/datadog/ci/contrib/rspec/knapsack_pro/patcher.rb, lib/datadog/ci/contrib/rspec/knapsack_pro/runner.rb, lib/datadog/ci/contrib/rspec/patcher.rb, lib/datadog/ci/contrib/rspec/runner.rb, sig/datadog/ci/contrib/rspec/knapsack_pro/patcher.rbs, spec/datadog/ci/contrib/knapsack_rspec/instrumentation_spec.rb, spec/datadog/ci/contrib/knapsack_rspec_go/instrumentation_spec.rb, spec/datadog/ci/contrib/knapsack_rspec_go/suite_under_test/some_test_rspec.rb, spec/datadog/ci/contrib/rspec/instrumentation_spec.rb, spec/knapsack_helper.rb, spec/support/contexts/ci_mode.rb, vendor/rbs/knapsack_pro/0/knapsack_pro.rbs, vendor/rbs/rspec/0/rspec.rbs
Fixes #147
This PR fixes the following issues with our current Knapsack Pro support:
**Dropping tests because of missing test session**
When running `knapsack_pro:rspec:queue` command, `Datadog.configure` block gets called when `rails_helper` is required which in this case happens after `KnapsackPro::Extensions::RSpecExtension.setup!` had been run. 
To fix this, we check whether `RSpec::Core::Runner` was already instrumented by knapsack: if yes, we instrument `RSpec::Core::Runner` directly. If not, we hook into `KnapsackPro::Extensions::RSpecExtension` to instrument the runner after knapsack injects its methods:
```ruby
if defined?(::KnapsackPro::Extensions::RSpecExtension::Runner) &&
::RSpec::Core::Runner.ancestors.include?(::KnapsackPro::Extensions::RSpecExtension::Runner) …
```
=> [CIVIS-10061] Fix Knapsack Pro integration

spec/datadog/ci/contrib/minitest/instrumentation_spec.rb, spec/datadog/ci/git/local_repository_spec.rb
Very minor improvements for gem's CI as a follow up to the updated jruby 9.4 image
=> [NO-TICKET] reenable git specs for jruby and delete useless flaky spec

Rakefile, spec/ddcov/calculator_with_symlinks/calculator.rb, spec/ddcov/calculator_with_symlinks/operations/add.rb, spec/ddcov/calculator_with_symlinks/operations/divide.rb, spec/ddcov/calculator_with_symlinks/operations/helpers/calculator_logger.rb, spec/ddcov/calculator_with_symlinks/operations/multiply.rb, spec/ddcov/calculator_with_symlinks/operations/operations.rb, spec/ddcov/calculator_with_symlinks/operations/subtract.rb, spec/ddcov/calculator_with_symlinks/vendor/gems/operations, spec/ddcov/ddcov_with_symlinks_spec.rb
This PR adds a test to assert that code coverage tool gets correct file paths when dependencies are located in symlinked folder and required via single entrypoint (emulating usage of local dependencies that are just symlinks to modules in minirepo).
**Motivation**
Make sure that code coverage won't break in the future as this is known case for the monorepo setup.
This PR adds only unit tests.
=> [NO TICKET] test code coverage with symlinked dependency required via entrypoint

ext/datadog_cov/datadog_cov.c, lib/datadog/ci/itr/coverage/writer.rb, sig/datadog/ci/itr/coverage/ddcov.rbs, sig/datadog/ci/itr/coverage/writer.rbs, spec/ddcov/ddcov_spec.rb
Applies the following changes and optimizations to per test code coverage:
- removes lines code coverage mode as it is not used and is not going to be used in the near future, so it is just a dead code right now
- caches last seen filename pointer so that if we cover sequential lines in the same file we skip prefix check and saving file name in the coverage hash table
- `dd_cov_data->root` and `dd_cov_data->ignored_path` are now copied (once) in malloc'd memory and stored as C-strings
- to avoid string copying, `rb_profile_frames` function is now used to store filename in resulting hash: it improves performance and solves UTF-8 filenames issue
Tested using test-environment integration test stand: …
=> [SDTEST-138] code coverage extension fixes and improvements

lib/datadog/ci.rb, lib/datadog/ci/contrib/cucumber/formatter.rb, lib/datadog/ci/contrib/minitest/runnable.rb, lib/datadog/ci/contrib/minitest/runner.rb, lib/datadog/ci/contrib/minitest/test.rb, lib/datadog/ci/contrib/rspec/example.rb, lib/datadog/ci/contrib/rspec/example_group.rb, lib/datadog/ci/contrib/rspec/knapsack_pro/runner.rb, lib/datadog/ci/contrib/rspec/runner.rb, sig/datadog/ci/contrib/cucumber/formatter.rbs, sig/datadog/ci/contrib/minitest/runnable.rbs, sig/datadog/ci/contrib/minitest/runner.rbs, sig/datadog/ci/contrib/minitest/test.rbs, sig/datadog/ci/contrib/rspec/example.rbs, sig/datadog/ci/contrib/rspec/example_group.rbs, sig/datadog/ci/contrib/rspec/knapsack_pro/runner.rbs, sig/datadog/ci/contrib/rspec/runner.rbs, spec/datadog/ci/contrib/ci_queue_rspec/instrumentation_spec.rb, spec/datadog/ci/contrib/cucumber/instrumentation_spec.rb, spec/datadog/ci/contrib/knapsack_rspec/instrumentation_spec.rb, spec/datadog/ci/contrib/knapsack_rspec_go/instrumentation_spec.rb, spec/datadog/ci/contrib/minitest/instrumentation_spec.rb, spec/datadog/ci/contrib/rspec/instrumentation_spec.rb, spec/datadog/ci_spec.rb
Tracks manual_api_events metric when public API is used.
Internal instrumentations don't use public API anymore.
=> [SDTEST-116] Implement manual_api_events metric

lib/datadog/ci/ext/telemetry.rb, lib/datadog/ci/test_optimisation/component.rb, lib/datadog/ci/test_optimisation/telemetry.rb, sig/datadog/ci/ext/telemetry.rbs, sig/datadog/ci/test_optimisation/telemetry.rbs, spec/datadog/ci/test_optimisation/component_spec.rb, spec/datadog/ci/test_optimisation/telemetry_spec.rb
Adds code coverage metrics to internal telemetry.
Note that code_coverage.errors metric is unused and remove. Code coverage collection in this library is "error-free" as any potential fatal bug in native extension will most likely cause segfault and crash of the Ruby process.
=> [SDTEST-160] Implement code coverage metrics for internal telemetry

lib/datadog/ci/git/local_repository.rb, lib/datadog/ci/git/telemetry.rb, lib/datadog/ci/test_visibility/component.rb, lib/datadog/ci/test_visibility/context.rb, sig/datadog/ci/git/local_repository.rbs, sig/datadog/ci/git/telemetry.rbs, sig/datadog/ci/test_visibility/context.rbs, spec/datadog/ci/configuration/components_spec.rb, spec/datadog/ci/contrib/cucumber/instrumentation_spec.rb, spec/datadog/ci/contrib/minitest/instrumentation_spec.rb, spec/datadog/ci/contrib/rspec/instrumentation_spec.rb, spec/datadog/ci/git/local_repository_spec.rb, spec/datadog/ci/git/telemetry_spec.rb, spec/datadog/ci/transport/http_spec.rb
Adds telemetry metrics collection to git commands
This change caused curious fail: one must not access Telemetry when the library is initialized. We previously collected environment tags during the library initialization stage, which might include using git commands. I made the environment tags collection lazy, so it does not happen until at least one span is traced.
=> [SDTEST-160] git commands telemetry

lib/datadog/ci/ext/telemetry.rb, lib/datadog/ci/git/search_commits.rb, lib/datadog/ci/git/tree_uploader.rb, lib/datadog/ci/git/upload_packfile.rb, lib/datadog/ci/test_optimisation/component.rb, lib/datadog/ci/test_optimisation/skippable.rb, lib/datadog/ci/transport/adapters/net.rb, lib/datadog/ci/transport/event_platform_transport.rb, lib/datadog/ci/transport/http.rb, lib/datadog/ci/transport/remote_settings_api.rb, lib/datadog/ci/transport/telemetry.rb, sig/datadog/ci/ext/telemetry.rbs, sig/datadog/ci/git/search_commits.rbs, sig/datadog/ci/test_optimisation/skippable.rbs, sig/datadog/ci/transport/adapters/net.rbs, sig/datadog/ci/transport/http.rbs, sig/datadog/ci/transport/remote_settings_api.rbs, sig/datadog/ci/transport/telemetry.rbs, spec/datadog/ci/contrib/knapsack_rspec/instrumentation_spec.rb, spec/datadog/ci/contrib/knapsack_rspec_go/instrumentation_spec.rb, spec/datadog/ci/git/search_commits_spec.rb, spec/datadog/ci/git/tree_uploader_spec.rb, spec/datadog/ci/git/upload_packfile_spec.rb, spec/datadog/ci/test_optimisation/component_spec.rb, spec/datadog/ci/test_optimisation/skippable_spec.rb, spec/datadog/ci/transport/http_spec.rb, spec/datadog/ci/transport/remote_settings_api_spec.rb, spec/datadog/ci/transport/telemetry_spec.rb
Adds the following metrics:
- git_requests.search_commits
- git_requests.search_commits_ms
- git_requests.search_commits_errors
- git_requests.objects_pack
- git_requests.objects_pack_ms
- git_requests.objects_pack_errors
- git_requests.objects_pack_bytes
- git_requests.objects_pack_files
- git_requests.settings
- git_requests.settings_ms
- git_requests.settings_errors
- git_requests.settings_response
- itr_skippable_tests.request
- itr_skippable_tests.request_ms
- itr_skippable_tests.request_errors
- itr_skippable_tests.response_bytes
- itr_skippable_tests.response_tests
=> [SDTEST-160] API metrics

lib/datadog/ci/ext/environment.rb, lib/datadog/ci/ext/environment/providers/appveyor.rb, lib/datadog/ci/ext/environment/providers/aws_code_pipeline.rb, lib/datadog/ci/ext/environment/providers/azure.rb, lib/datadog/ci/ext/environment/providers/bitbucket.rb, lib/datadog/ci/ext/environment/providers/bitrise.rb, lib/datadog/ci/ext/environment/providers/buddy.rb, lib/datadog/ci/ext/environment/providers/buildkite.rb, lib/datadog/ci/ext/environment/providers/circleci.rb, lib/datadog/ci/ext/environment/providers/codefresh.rb, lib/datadog/ci/ext/environment/providers/github_actions.rb, lib/datadog/ci/ext/environment/providers/gitlab.rb, lib/datadog/ci/ext/environment/providers/jenkins.rb, lib/datadog/ci/ext/environment/providers/teamcity.rb, lib/datadog/ci/ext/environment/providers/travis.rb, lib/datadog/ci/ext/telemetry.rb, lib/datadog/ci/test_visibility/component.rb, lib/datadog/ci/test_visibility/telemetry.rb, sig/datadog/ci/ext/environment.rbs, sig/datadog/ci/ext/telemetry.rbs, sig/datadog/ci/test_visibility/telemetry.rbs, spec/datadog/ci/test_visibility/component_spec.rb, spec/datadog/ci/test_visibility/telemetry_spec.rb
Adds test_session metric with provider tag to track which CI providers are used
Unit tests
=> [SDTEST-415] Add test_session metric

lib/datadog/ci/ext/telemetry.rb, lib/datadog/ci/test_visibility/telemetry.rb, sig/datadog/ci/ext/telemetry.rbs, sig/datadog/ci/test_visibility/telemetry.rbs, spec/datadog/ci/test_visibility/telemetry_spec.rb
Send the same provider tag values to citestcycle and telemetry
=> [SDTEST-415] remove telemetry-specific provider tags

lib/datadog/ci/contrib/minitest/runner.rb, lib/datadog/ci/contrib/minitest/test.rb, lib/datadog/ci/contrib/rspec/example.rb, lib/datadog/ci/test_retries/component.rb, lib/datadog/ci/test_visibility/component.rb, lib/datadog/ci/test_visibility/null_component.rb, sig/datadog/ci/contrib/minitest/runner.rbs, sig/datadog/ci/contrib/minitest/test.rbs, sig/datadog/ci/test_retries/component.rbs, sig/datadog/ci/test_visibility/component.rbs, sig/datadog/ci/test_visibility/null_component.rbs, spec/datadog/ci/contrib/minitest/instrumentation_spec.rb, spec/datadog/ci/contrib/rspec/instrumentation_spec.rb, spec/datadog/ci/test_retries/component_spec.rb, spec/datadog/ci/test_visibility/component_spec.rb
Adds [auto test retries](https://docs.datadoghq.com/tests/auto_test_retries?tab=java#explore-results-in-the-test-visibility-explorer) support for minitest
Feature is covered by unit tests in `minitest/instrumentation_spec.rb`
Tested using Sidekiq in this commit: https://github.com/anmarchenko/sidekiq/commit/020ca88eaa8de24dcaee6428e6076963d5a5d4ab
Local test run ends successfully: 
New flaky test is detected by Datadog:
Correct test runs are traced:
Retries can be filtered using `test.is_retry` tag:
Test session is reported as passed:
=> [SDTEST-437] Auto test retries for minitest

lib/datadog/ci/contrib/rspec/example.rb, spec/datadog/ci/contrib/rspec/instrumentation_spec.rb, vendor/rbs/rspec/0/rspec.rbs
When rspec process is being killed by INT signal, it still runs the current test until the end. 
If some resources (e.g. databases) are being decomissioned before the test ends, then datadog-ci traces this error and sends it to the backend. This might create noise for the users because of irrelevant errors.
This PR checks `RSpec.world.wants_to_quit` variable after running each test. If RSpec is quitting, we do not set error for the current span.
**Motivation**
Customer reports that datadog-ci reports test failures when infrastructure (db) is down after CI job is canceled .
Unit test is provided
=> [SDTEST-666] RSpec - don't report test errors if rspec process is quitting

lib/datadog/ci/configuration/settings.rb, spec/datadog/ci/configuration/settings_spec.rb
As ITR is out of beta for Ruby, now it can be enabled or disabled using Datadog test service settings page.
Environment variable `DD_CIVISIBILITY_ITR_ENABLED` can still be used as a killswitch to forcefully disable ITR from the library side.
Unit tests
=> [SDTEST-579] make itr_enabled config parameter true by default

lib/datadog/ci/git/local_repository.rb, spec/datadog/ci/git/local_repository_spec.rb
Our current git unshallowing command is optimised, but it might fail under a different circumstances.
For example `git rev-parse HEAD` fails if the local HEAD is a commit that has not been pushed to the remote.
We will add the following fallbacks:
- ` $(git rev-parse --abbrev-ref --symbolic-full-name @{upstream})` - we try this first, but it might fail too if the CI is working on a detached HEAD or maybe branch tracking hasn’t been set up
- provide no remote as a last resort
**Motivation**
Improve git unshallowing resilience
Unit test is provided
=> [SDTEST-126] add different fallbacks for unshallowing remotes

ext/datadog_cov/datadog_cov.c, spec/ddcov/app/model/my_model_❤️.rb, spec/ddcov/ddcov_spec.rb
Fixes potential crash from the test impact analysis native extension when `Object.const_source_location` unexpectedly returns weird values. Adds more testing for these cases.
**Motivation**
We got reports of datadog_cov native extension crashes via telemetry crashtracker: while the root cause is unknown yet, this fix is an attempt to mitigate one of the possible causes
=> [SDTEST-755] attempt to fix datadog_cov crash when doing allocation profiling

lib/datadog/ci/test.rb, lib/datadog/ci/test_optimisation/component.rb, sig/datadog/ci/test.rbs, spec/datadog/ci/test_optimisation/component_spec.rb, spec/datadog/ci/test_spec.rb, spec/support/contexts/telemetry_spy.rb
- Sends `code_coverage_is_empty` telemetry metric only when code coverage is empty and test was not skipped
- Adds additional unit tests for skipped tests metric
=> [SDTEST-740] Minor telemetry fixes

.github/workflows/add-milestone-to-pull-requests.yml
Fixes "Add milestone" github action by adding missing permission
**Motivation**
"Add milestone" was broken since default permissions were updated for the repository
=> [NO-TICKET] fix permissions for milestone action

lib/datadog/ci/ext/test.rb, lib/datadog/ci/span.rb, lib/datadog/ci/test_visibility/context.rb, lib/datadog/ci/utils/test_run.rb, sig/datadog/ci/ext/test.rbs, sig/datadog/ci/span.rbs, sig/datadog/ci/utils/test_run.rbs, spec/datadog/ci/test_visibility/component_spec.rb, spec/datadog/ci/test_visibility/serializers/test_v1_spec.rb, spec/datadog/ci/test_visibility/serializers/test_v2_spec.rb, spec/datadog/ci/utils/test_run_spec.rb
Sends internal metric `_dd.host.vcpu_count` for all test visibility events. This metric contains value of the virtual processors that are available to the Ruby process that runs the test suite.
**Motivation**
It enables Datadog backend to compute the infrastructure cost savings provided by ITR.
Unit tests are provided.
Tested using middleman on staging (with internal feature flag that show hidden event metadata):
=> [SDTEST-865] Send internal vCPU count metric

lib/datadog/ci/contrib/cucumber/formatter.rb, lib/datadog/ci/contrib/minitest/helpers.rb, lib/datadog/ci/contrib/minitest/runnable.rb, lib/datadog/ci/contrib/rspec/example_group.rb, lib/datadog/ci/span.rb, lib/datadog/ci/test.rb, lib/datadog/ci/test_visibility/component.rb, sig/datadog/ci/contrib/cucumber/formatter.rbs, sig/datadog/ci/contrib/minitest/helpers.rbs, sig/datadog/ci/span.rbs, sig/datadog/ci/test.rbs, sig/datadog/ci/test_visibility/component.rbs, spec/datadog/ci/contrib/cucumber/instrumentation_spec.rb, spec/datadog/ci/contrib/minitest/instrumentation_spec.rb, spec/datadog/ci/contrib/rspec/instrumentation_spec.rb, vendor/rbs/rspec/0/rspec.rbs
Adds `test.source.file`, `test.source.start`, `test.codeowners` tags to test suites reported to Datadog
**Motivation**
We want to show source locations for test suites and attach codeowners to test suites
RSpec (tested using rubocop):
Minitest (tested using feedbin):
Cucumber (tested using middleman):
=> [SDTEST-301] add source location info to test suites

Steepfile, lib/datadog/ci.rb, lib/datadog/ci/contrib/simplecov/configuration/settings.rb, lib/datadog/ci/contrib/simplecov/ext.rb, lib/datadog/ci/contrib/simplecov/integration.rb, lib/datadog/ci/contrib/simplecov/patcher.rb, lib/datadog/ci/contrib/simplecov/result_extractor.rb, lib/datadog/ci/ext/test.rb, lib/datadog/ci/test_visibility/component.rb, lib/datadog/ci/test_visibility/total_coverage.rb, sig/datadog/ci/contrib/simplecov/configuration/settings.rbs, sig/datadog/ci/contrib/simplecov/ext.rbs, sig/datadog/ci/contrib/simplecov/integration.rbs, sig/datadog/ci/contrib/simplecov/patcher.rbs, sig/datadog/ci/contrib/simplecov/result_extractor.rbs, sig/datadog/ci/ext/test.rbs, sig/datadog/ci/test_visibility/total_coverage.rbs, spec/datadog/ci/contrib/cucumber/instrumentation_spec.rb, spec/datadog/ci/contrib/minitest/instrumentation_spec.rb, spec/datadog/ci/contrib/rspec/instrumentation_spec.rb, vendor/rbs/simplecov/0/simplecov.rbs
Adds support for [total code coverage reporting](https://docs.datadoghq.com/tests/code_coverage) feature. 
Supported code coverage library: `gem "simplecov" >= 0.18.0`
**Motivation**
Achieving feature parity across Datadog libraries
Tested using rubocop project:
... and middleman:
=> [SDTEST-60] Report total lines coverage percentage to Datadog

lib/datadog/ci/ext/transport.rb, lib/datadog/ci/transport/http.rb, sig/datadog/ci/ext/transport.rbs, sig/datadog/ci/transport/http.rbs, spec/datadog/ci/transport/http_spec.rb
Expands failed requests retry logic for HTTP client in this library to be as follows:
1. If response HTTP code is 5xx, retry up to 3 times with exponential backoff
2. If response HTTP code is 429, retry up to 3 times, take backoff value from `X-RateLimit-Reset` response header (stop retrying if backoff value is over 30)
3. If response HTTP code is 4xx (but not 429), fail immediately without retries
4. If exception is raised due to network issues, retry up to 3 times with exponential backoff
**Motivation**
Better handling of transient server errors and rate limit hits: we have some requests failing with 429/503 according to internal telemetry
Unit tests are provided for each of the above cases
=> [SDTEST-292] Retry HTTP requests on 429 and 5xx responses

lib/datadog/ci/git/local_repository.rb, lib/datadog/ci/transport/http.rb, spec/datadog/ci/test_optimisation/coverage/event_spec.rb
Applies some heuristics to avoid calling `Pathname#relative_path_from` function when determining what would be path relative to the git root for the given filepath:
- If given filepath is absolute, we use the fact that absolute paths are pre-filtered already and they always contain root as prefix, so we only need to slice the string to get the suffix (`path[prefix_length..]`)
- If given filepath is relative, we compute `Pathname#relative_path_from` once and then we store the difference between the relative filepath and the computed relative path from root in the `@prefix_to_root` cached variable. We can do it because all relative paths are computed relative to the `Dir.pwd` which doesn't change in the lifetime of the process. After we have `@prefix_to_root` …
=> [SDTEST-878] Optimise LocalRepository.relative_to_root helper to make test impact analysis faster

.github/workflows/test-memory-leaks.yml, Gemfile, Rakefile, spec/datadog/ci/release_gem_spec.rb, suppressions/ruby-3.4.supp
Adds https://github.com/Shopify/ruby_memcheck gem to automatically find and report memory leaks using [valgrind](https://valgrind.org/). This PR mostly copies the setup from dd-trace-rb which was done in https://github.com/DataDog/dd-trace-rb/pull/3852
**Motivation**
Prevent memory leaks from the native extension
Github Actions workflow is added
=> [SDTEST-744] add memory leaks tests with ruby_memcheck

lib/datadog/ci/configuration/components.rb, sig/datadog/ci/configuration/components.rbs, spec/datadog/ci/contrib/timecop/instrumentation_spec.rb, vendor/rbs/timecop/0/timecop.rbs
Automatically configures correct monotonic clock provider for tracing module if timecop library mocked monotonic time. 
**Motivation**
Timecop v0.9.9 allows to [mock monotonic clock](https://github.com/travisjeffery/timecop/pull/419), which might affect displayed tests duration in Datadog UI.
Unit test is provided
=> [SDTEST-482] Use correct monotonic clock time if Timecop.mock_process_clock is set

lib/datadog/ci/cli/command/base.rb, lib/datadog/ci/cli/command/skippable_tests_percentage.rb, spec/datadog/ci/cli/cli_spec.rb, spec/datadog/ci/cli/command/skippable_tests_percentage_estimate_spec.rb, spec/datadog/ci/cli/command/skippable_tests_percentage_spec.rb
Adds option --spec-path to skipped-tests-estimate CLI command
**Motivation**
Because of the bug this option isn't available now (but it should be)
Added more unit tests
=> Make --spec-path option available to skipped-tests-estimate cli command

lib/datadog/ci.rb, lib/datadog/ci/contrib/ciqueue/integration.rb, lib/datadog/ci/contrib/ciqueue/patcher.rb, lib/datadog/ci/contrib/rspec/integration.rb, sig/datadog/ci/contrib/ciqueue/integration.rbs, sig/datadog/ci/contrib/ciqueue/patcher.rbs
Similarly to https://github.com/DataDog/datadog-ci-rb/pull/253 we extract ci-queue to its own integration.
**Motivation**
Needed by auto-instrumentation feature
Covered by existing unit tests
=> [SDTEST-1129] extract ciqueue instrumentation

.standard_todo.yml, README.md, Rakefile, exe/ddcirb, lib/datadog/ci/auto_instrument.rb, lib/datadog/ci/cli/cli.rb, lib/datadog/ci/cli/command/exec.rb, lib/datadog/ci/contrib/cucumber/integration.rb, lib/datadog/ci/contrib/instrumentation.rb, lib/datadog/ci/contrib/integration.rb, lib/datadog/ci/contrib/minitest/integration.rb, lib/datadog/ci/contrib/patcher.rb, lib/datadog/ci/contrib/rspec/integration.rb, lib/datadog/ci/test_retries/strategy/retry_new.rb, sig/datadog/ci/cli/cli.rbs, sig/datadog/ci/cli/command/exec.rbs, sig/datadog/ci/contrib/instrumentation.rbs, sig/datadog/ci/contrib/integration.rbs, spec/datadog/ci/cli/cli_spec.rb, spec/datadog/ci/contrib/knapsack_auto_instrument/instrumentation_spec.rb, spec/datadog/ci/contrib/minitest_auto_instrument/instrumentation_spec.rb
Allows Ruby test runs to be autoinstrumented without code changes (via RUBYOPT env variable or datadog-ci CLI).
Example using RUBYOPT:
`RUBYOPT="-rbundler/setup -rdatadog/ci/auto_instrument" bundle exec rake test`
Example using ddcirb CLI tool:
`bundle exec ddcirb exec bundle exec rake test`
**Motivation**
Easier onboarding
There are integration tests provided, also tested using a number of open source projects' forks
=> [SDTEST-228] Auto instrumentation

lib/datadog/ci/auto_instrument.rb, lib/datadog/ci/contrib/instrumentation.rb, lib/datadog/ci/test_visibility/telemetry.rb, sig/datadog/ci/contrib/instrumentation.rbs, spec/datadog/ci/contrib/minitest/instrumentation_spec.rb, spec/datadog/ci/contrib/minitest_auto_instrument/instrumentation_spec.rb
Adds a couple of small fixes to auto instrumentation:
- `test_session` telemetry metric has now auto_injected tag set to true when auto instrumentation was used
- when auto instrumentation is used on JRuby, we print error message and bail out of instrumenting tests
=> [SDTEST-228] Send auto_injected: true to internal telemetry when auto instrumentation was used

.github/workflows/add-milestone-to-pull-requests.yml, .github/workflows/build-gem.yml, .github/workflows/codeql-analysis.yml, .github/workflows/datadog-sca.yml, .github/workflows/datadog-static-analysis.yml, .github/workflows/integration-test.yml, .github/workflows/publish.yml, .github/workflows/yard.yml
**Motivation:**
https://github.blog/changelog/2024-11-05-notice-of-breaking-changes-for-github-actions/#ubuntu-latest-upcoming-breaking-changes
>We will migrate the ubuntu-latest label to ubuntu 24 starting on December 5, 2024 and ending on January 17, 2025. The ubuntu 24 image has a different set of tools and packages than ubuntu 22. We have made cuts to the list of packages so that we can maintain our SLA for free disk space. This may break your workflows if you depend on certain packages that have been removed. Please review this [list](https://github.com/actions/runner-images/issues/10636) to see if you are using any affected packages.
Pin to ubuntu 22 instead of `latest`
=> Pin ubuntu 22.04

lib/datadog/ci/contrib/rspec/example.rb, lib/datadog/ci/contrib/rspec/example_group.rb, lib/datadog/ci/test.rb, lib/datadog/ci/test_optimisation/component.rb, sig/datadog/ci/contrib/rspec/example.rbs, sig/datadog/ci/contrib/rspec/example_group.rbs, sig/datadog/ci/test.rbs, sig/datadog/ci/test_optimisation/component.rbs, spec/datadog/ci/contrib/rspec/instrumentation_spec.rb, spec/datadog/ci/test_visibility/transport_spec.rb, vendor/rbs/rspec/0/rspec.rbs
Closes #256
Improves handling of RSpec context hooks when tests are skipped by test impact analysis: now we will skip context hooks if we know that all examples in the context are going to be skipped by Datadog.
**Motivation**
See #256
This PR doesn't address another limitation of context hooks with test impact analysis: when we collect impacted files for test (aka per test code coverage), we don't cover context hooks (because they cannot be attributed to any single test). This can lead to skipping tests that should not be skipped. I reprioritised the issue with context hooks coverage higher because there is new evidence that context hooks are being used by our customers.
=> [SDTEST-1229] Skip before(:all) context hooks when all examples are skipped

lib/datadog/ci/codeowners/matcher.rb, spec/datadog/ci/codeowners/matcher_spec.rb
Fixes a bug with handling of inline comments in CODEOWNERS:
```
/path/to/file.rb @owner1 @owner2 #This is an inline comment.
```
Before this fix it produced the following list of owners:
```ruby
["@owner1", "@owner2", "#This", "is", "an", "inline", "comment."]
```
After the fix:
```ruby
["@owner1", "@owner2"]
```
Unit tests
=> [SDTEST-1304] Fix inline comments handling when parsing CODEOWNERS files

lib/datadog/ci/ext/test.rb, lib/datadog/ci/test_visibility/context.rb, lib/datadog/ci/utils/configuration.rb, sig/datadog/ci/ext/test.rbs, sig/datadog/ci/utils/configuration.rbs, spec/datadog/ci/contrib/minitest/instrumentation_spec.rb, spec/datadog/ci/utils/configuration_spec.rb, spec/support/contexts/ci_mode.rb
Sends _dd.test.is_user_provided_service tag for all spans: true if user has configured test_service, false if we send default value
**Motivation**
Internal accounting
=> [SDTEST-1245] Internal: send _dd.test.is_user_provided_service tag to track if test_service is configured

lib/datadog/ci/transport/event_platform_transport.rb, sig/datadog/ci/transport/event_platform_transport.rbs
Decreases the max payload size for events (test visibility and test impact analysis) to 4.5MB.
Maximal event size for Datadog intake is 5MB but we need to leave some buffer for package headers.
**Motivation**
Elevated rate of 413 (Request entity too large) errors seen in internal telemetry for Ruby library
Not needed
=> [SDTEST-1376] set the max payload size for events to 4.5MB

lib/datadog/ci/test_session.rb, lib/datadog/ci/test_visibility/serializers/base.rb, lib/datadog/ci/test_visibility/serializers/test_session.rb, sig/datadog/ci/test_visibility/serializers/base.rbs, spec/datadog/ci/test_session_spec.rb, spec/datadog/ci/test_visibility/component_spec.rb, spec/datadog/ci/test_visibility/serializers/test_session_spec.rb
Previously we used test command as part of span resource name (we show it in the trace view). 
It would be more correct to use logical test session name for this purpose: it can be configured by the user with DD_TEST_SESSION_NAME env variable. By default, it is constructed from CI job name + test command.
Note: this doesn't change the test session's fingerprint, only the presentation in trace view
**Motivation**
Step by step prepare to the future use of DD_TEST_SESSION_NAME as a logical name for test sessions
=> [SDTEST-1375] Use logical test session name as part of test session span's resource instead of test command

lib/datadog/ci/version.rb
Bumps maximum Ruby version to 3.5
Closes https://github.com/DataDog/datadog-ci-rb/issues/273
**Motivation**
Ruby 3.4 is released
Ruby 3.4 is tested by unit tests since some time
=> [NOTICKET-1] bump maximum Ruby version to 3.5

.github/workflows/test-memory-leaks.yml
Fixes previously failing test-memcheck job by using released Ruby version 3.4.1 instead of Ruby 3.4.0-preview
**Motivation**
CI started to fail
CI is green
=> [NOTICKET-1] use released Ruby 3.4.1 for memory leaks check

spec/datadog/ci/release_gem_spec.rb
Tests that MAXIMUM_RUBY_VERSION is same for datadog and datadog-ci gems so that we don't forget to bump it for both of them.
**Motivation**
See issue https://github.com/DataDog/datadog-ci-rb/issues/273
This is a unit test
=> [SDTEST-1408] test that MAXIMUM_RUBY_VERSION is same for datadog and datadog-ci gems

.github/workflows/add-milestone-to-pull-requests.yml, .github/workflows/build-gem.yml, .github/workflows/check.yml, .github/workflows/codeql-analysis.yml, .github/workflows/datadog-static-analysis.yml, .github/workflows/integration-test.yml, .github/workflows/publish.yml, .github/workflows/test-memory-leaks.yml, .github/workflows/test.yml, .github/workflows/yard.yml, tasks/github.rake
Github Actions will now use Ubuntu 24.04 and Ruby 3.4 for the library's own CI
**Motivation**
Use newer versions of Ruby and Ubuntu
If CI is green, it works
=> [SDTEST-1410] bump CI dependencies: Ruby 3.4, Ubuntu 24.04

lib/datadog/ci/configuration/components.rb, lib/datadog/ci/ext/environment.rb, lib/datadog/ci/ext/environment/providers/github_actions.rb, lib/datadog/ci/test_optimisation/component.rb, lib/datadog/ci/test_visibility/transport.rb, sig/datadog/ci/test_visibility/transport.rbs, spec/datadog/ci/test_visibility/transport_spec.rb
Send error logs to Datadog's internal telemetry in some cases
**Motivation**
Improve our ability to troubleshoot library errors
=> [SDTEST-741] Add telemetry logs

lib/datadog/ci/contrib/minitest/helpers.rb, lib/datadog/ci/contrib/minitest/runnable.rb, lib/datadog/ci/contrib/minitest/runner.rb, lib/datadog/ci/contrib/minitest/test.rb, lib/datadog/ci/span.rb, lib/datadog/ci/test_suite.rb, lib/datadog/ci/test_visibility/component.rb, lib/datadog/ci/test_visibility/context.rb, lib/datadog/ci/test_visibility/store/global.rb, sig/datadog/ci/contrib/minitest/helpers.rbs, sig/datadog/ci/contrib/minitest/runner.rbs, sig/datadog/ci/test_suite.rbs, sig/datadog/ci/test_visibility/component.rbs, sig/datadog/ci/test_visibility/context.rbs, sig/datadog/ci/test_visibility/store/global.rbs, spec/datadog/ci/contrib/ci_queue_minitest/instrumentation_spec.rb, spec/datadog/ci/contrib/minitest/instrumentation_spec.rb, spec/support/coverage_helpers.rb
Adds parallel test suites to minitest tracing. 
**Motivation**
Fixing a long standing issue that we didn't have proper support for parallel executors in minitest
Tested using quotes-rails project:
=> [SDTEST-161] add parallel testing support to minitest framework

lib/datadog/ci/contrib/rspec/example.rb, lib/datadog/ci/contrib/rspec/example_group.rb, lib/datadog/ci/test_management/component.rb, lib/datadog/ci/test_optimisation/component.rb, sig/datadog/ci/contrib/rspec/example.rbs, sig/datadog/ci/contrib/rspec/example_group.rbs, sig/datadog/ci/test_management/component.rbs, sig/datadog/ci/test_optimisation/component.rbs, spec/datadog/ci/contrib/rspec/instrumentation_spec.rb, spec/datadog/ci/test_management/component_spec.rb
Prevents test impact analysis from skipping any tests with "attempt to fix" property (that means that developer tries to fix this flaky test).
**Motivation**
When developer tries to fix a flaky test we don't want the test to be skipped by test impact analysis. Note that this situation is purely theoretical because if there code changes related to a test, test impact analysis is not going to skip it anyway. Still, we make it even theoretically impossible.
Tests are provided
=> [SDTEST-1753] Fix: prevent test impact analysis from skipping flaky tests that are attempted to be fixed

.github/workflows/update-latest-dependencies.yml
Automates development dependency updates for Ruby versions 2.7 - 3.4
**Motivation**
As we use gem `datadog` dependency from master now we need to update it more often
Note that jruby is excluded from automated updates for now: there is another issue with psych installation on jruby
First automated PR is created:
https://github.com/DataDog/datadog-ci-rb/pull/315
=> [NO-TICKET] Internal: workflow to automatically update dependencies

lib/datadog/ci/ext/test.rb, lib/datadog/ci/test_retries/component.rb, spec/datadog/ci/contrib/minitest/instrumentation_spec.rb, spec/datadog/ci/contrib/rspec/instrumentation_spec.rb, spec/datadog/ci/test_retries/component_spec.rb, spec/datadog/ci/test_visibility/transport_spec.rb
Sends tag `attempt_to_fix_passed:false` when attempt to fix validation didn't succeed. Bumps libraries capabilities version for attempt_to_fix
=> [SDTEST-1961] Send `attempt_to_fix_passed:false` when attempt_to_fix_validation did not succeed

lib/datadog/ci/ext/test.rb, lib/datadog/ci/test_management/tests_properties.rb, spec/datadog/ci/test_management/tests_properties_spec.rb, spec/datadog/ci/test_visibility/transport_spec.rb
Add sha parameter to the tests_properties request
**Motivation**
Last detail we need for flaky test remediation to work
=> [SDTEST-1985] flaky test management: add sha parameter to the tests_properties request

lib/datadog/ci/ext/environment.rb, lib/datadog/ci/ext/environment/configuration_discrepancy_checker.rb, lib/datadog/ci/ext/telemetry.rb, sig/datadog/ci/ext/environment/configuration_discrepancy_checker.rbs, sig/datadog/ci/ext/telemetry.rbs, spec/datadog/ci/ext/environment/configuration_discrepancy_checker_spec.rb, spec/datadog/ci/ext/environment_spec.rb
Sends metrics to Datadog telemetry when git.commit.sha and git.repository_url values are different between CI information / user-provided configs / local git repository info.
**Motivation**
Understand better customers' setups
=> [SDTEST-1919] Internal: send telemetry metric when there are discrepancies in git information

lib/datadog/ci/test_visibility/component.rb, lib/datadog/ci/test_visibility/transport.rb, sig/datadog/ci/test_visibility/transport.rbs, spec/datadog/ci/test_visibility/transport_spec.rb
Improves Datadog telemetry: ignore skipped Span events because it is very noisy but instead log all dropped events connected to Datadog Test Optimization
**Motivation**
I want to be able to investigate dropped test events better
=> [SDTEST-2193] Internal: telemetry logging improvements

lib/datadog/ci/contrib/rspec/integration.rb, lib/datadog/ci/contrib/rspec/patcher.rb
Attempts to fix https://github.com/DataDog/datadog-ci-rb/issues/380
We have a very curious bug report in an issue above where knapsack_pro tracing stops working after pretty innocuous minor version update of datadog-ci gem.  Examining the debug logs did not bring a lot of clarity: the tests seem to be running normally, APM tracing works, transport layer works - but not a single RSpec example traced. As if RSpec instrumentation wouldn't exist at all.
The only change between `1.19.0` and `1.20.2` that could cause this behaviour is this:
```ruby
!defined?(::RSpec::Core::Formatters::DocumentationFormatter).nil? &&
!defined?(::RSpec::Core::Formatters::BaseFormatter).nil? &&
!defined?(::RSpec::Core::Formatters::BaseTextFormatter).nil?
```
There is a possibility that it …
=> [BUGFIX] fix: RSpec's DocumentationFormatter might not be present at instrumentation time

lib/datadog/ci/ext/environment.rb, lib/datadog/ci/ext/environment/extractor.rb, lib/datadog/ci/ext/environment/providers/aws_code_pipeline.rb, lib/datadog/ci/ext/environment/providers/azure.rb, lib/datadog/ci/ext/environment/providers/base.rb, lib/datadog/ci/ext/environment/providers/buildkite.rb, lib/datadog/ci/ext/environment/providers/circleci.rb, lib/datadog/ci/ext/environment/providers/github_actions.rb, lib/datadog/ci/ext/environment/providers/gitlab.rb, sig/datadog/ci/ext/environment.rbs, sig/datadog/ci/ext/environment/providers/aws_code_pipeline.rbs, sig/datadog/ci/ext/environment/providers/azure.rbs, sig/datadog/ci/ext/environment/providers/base.rbs, sig/datadog/ci/ext/environment/providers/buildkite.rbs, sig/datadog/ci/ext/environment/providers/circleci.rbs, sig/datadog/ci/ext/environment/providers/gitlab.rbs, spec/datadog/ci/ext/environment/providers/azure_spec.rb, spec/datadog/ci/ext/environment/providers/buildkite_spec.rb, spec/datadog/ci/ext/environment/providers/circleci_spec.rb, spec/datadog/ci/ext/environment/providers/github_actions_spec.rb, spec/datadog/ci/ext/environment/providers/gitlab_spec.rb, spec/support/fixtures/ci/awscodepipeline.json, spec/support/fixtures/ci/azurepipelines.json, spec/support/fixtures/ci/buildkite.json, spec/support/fixtures/ci/circleci.json, spec/support/fixtures/ci/github.json, spec/support/fixtures/ci/gitlab.json
Adds `ci.job.id` tag
**Motivation**
We sent the information about the job.id in `_dd.ci.env.vars` but not in separate tag before - this was confusing
=> [SDTEST-2284] Add ci.job.id tag to events

lib/datadog/ci/contrib/minitest/helpers.rb, spec/datadog/ci/contrib/minitest/instrumentation_spec.rb
Fixes the crash when encountering relative paths for Minitest's test suites
**Motivation**
Fix https://github.com/DataDog/datadog-ci-rb/issues/386
Thanks @ebarajas for sending the fix
Unit test is provided
=> [SDTEST-2431] fix Minitest's test suite name when encountering relative source file paths

lib/datadog/ci/ext/environment.rb, lib/datadog/ci/ext/telemetry.rb, lib/datadog/ci/git/base_branch_sha_detector.rb, lib/datadog/ci/git/local_repository.rb, sig/datadog/ci/ext/telemetry.rbs, sig/datadog/ci/git/base_branch_sha_detector.rbs, sig/datadog/ci/git/local_repository.rbs, spec/datadog/ci/ext/environment_spec.rb, spec/datadog/ci/git/local_repository_integration_spec.rb
Changes the way we fetch head commit when doing impacted tests detection: before we were always fetching parent commit, now we fetch exact commit sha
**Motivation**
Increase precision of impacted tests feature
Unit tests
=> [SDTEST-2432] fetch exact head commit instead of unshallowing parent for impacted tests detection

lib/datadog/ci/ext/environment/extractor.rb, lib/datadog/ci/ext/environment/providers/base.rb, lib/datadog/ci/ext/environment/providers/github_actions.rb, lib/datadog/ci/ext/environment/providers/gitlab.rb, lib/datadog/ci/ext/git.rb, sig/datadog/ci/ext/environment/providers/base.rbs, sig/datadog/ci/ext/environment/providers/github_actions.rbs, sig/datadog/ci/ext/environment/providers/gitlab.rbs, sig/datadog/ci/ext/git.rbs, spec/datadog/ci/ext/environment/providers/github_actions_spec.rb, spec/datadog/ci/ext/environment/providers/gitlab_spec.rb
It turned out that what we used as base sha for Github Actions is in fact a head of base branch - this PR fixes it.
Also it adds base branch sha's for Gitlab.
Unit tests
=> [SDTEST-2355] Fix handling of base branch commit SHA for Github Actions and GItlab

lib/datadog/ci/test_discovery/component.rb, spec/datadog/ci/contrib/rspec/instrumentation_spec.rb, spec/datadog/ci/test_discovery/component_spec.rb
Outputs test suite's source file additionally to test's source file in test discovery mode
**Motivation**
Shared RSpec examples are defined in helper files, but executed in test suite files - we need to know where test suite is located to know where test is executed
=> [SDTEST-2479] in test discovery mode output suiteSourceFile for each test
